LaboratoriskaMVC1/Models/Friend.cs
namespace LaboratoriskaMVC1.Models
{
    using System.ComponentModel.DataAnnotations;

    public class Friend
    {
        public int ID { get; set; }
        [Required]
        [Display (Name = "Friend ID" )]
        [Range(1,200,ErrorMessage ="Vnesete broj od 0 do 200")]
        public int? FriendId { get; set; }

        [Required]
        [Display(Name = "Friend Name")]
        public string Ime { get; set; }

        [Required]
        [Display(Name = "Place")]
        public string MastoZiveenje { get; set; }
    }
}

LaboratoriskaMVC1/Controllers/FriendController.cs
namespace LaboratoriskaMVC1.Controllers
{
    using LaboratoriskaMVC1.Models;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Remoting.Messaging;
    using System.Security.Cryptography.X509Certificates;
    using System.Web.Mvc;

    public class FriendController : Controller
    {
        private static List<Friend> friends = new List<Friend>() {
            new Friend(){ ID = 1, FriendId = 120, Ime = "Margarita", MastoZiveenje = "Skopje" },
            new Friend(){ ID = 2, FriendId = 12, Ime = "Nenad", MastoZiveenje = "Skopje" }
        };


        // GET: Friend
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FriendView()
        {
            return View(friends);
        }


        public ActionResult NewFriend()
        {
            int lastIndex = friends.Max(x => x.ID);
            Friend model = new Friend() { ID = lastIndex+1 };
            return View(model);
        }

        [HttpPost]
        public ActionResult NewFriend(Friend model)
        {
            Friend friend = friends.FirstOrDefault(x => x.FriendId == model.FriendId);
            if(friend != null)
            {
                return View(model);
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            friends.Add(model);
            return View("FriendView", friends);

        }

        public ActionResult EditFriend(int id)
        {
            Friend friend = friends.First(x => x.ID == id);
            return View(friend);
        }

        [HttpPost]
        public ActionResult EditFriend(Friend model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Friend forUpdate = friends.First(x => x.ID == model.ID);
            forUpdate.FriendId = model.FriendId;
            forUpdate.Ime = model.Ime;
            forUpdate.MastoZiveenje = model.MastoZiveenje;

            return View("FriendView", friends);
        }


        public ActionResult DeleteFriend(int id)
        {
            Friend friend = friends.First(x => x.ID == id);
            friends.Remove(friend);
            return View("FriendView", friends);
        }

    }
}

LaboratoriskaMVC1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LaboratoriskaMVC1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LaboratoriskaMVC1/Views/Friend/EditFriend.cshtml
@model LaboratoriskaMVC1.Models.Friend

@{
    ViewBag.Title = "EditFriend";
}

<h2>Edit Friend</h2>

@using (Html.BeginForm("EditFriend", "Friend"))
{
    @Html.HiddenFor(m => m.ID)
    <div class="form-group">
        @Html.LabelFor(m => m.FriendId) @Html.TextAreaFor(m => m.FriendId, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.FriendId)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Ime) @Html.TextAreaFor(m => m.Ime, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Ime)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.MastoZiveenje) @Html.TextAreaFor(m => m.MastoZiveenje, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MastoZiveenje)
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
    @Html.ActionLink("Back", "FriendView", new { }, new { @class = "btn btn-primary" })
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LaboratoriskaMVC1/Views/Friend/FriendView.cshtml
@model List<LaboratoriskaMVC1.Models.Friend>
 
@{
    ViewBag.Title = "FriendView";
}

<h2>Friend table</h2>

<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>Friend Id</th>
        <th>Friend Name</th>
        <th>Place</th>
        <th> </th>
    </tr>
    @{

        foreach (var d in Model)
        {
            <tr>
                <td>@d.FriendId</td>
                <td>@d.Ime</td>
                <td>@d.MastoZiveenje</td>
                <td>
                    <a href="/Friend/EditFriend/@d.ID">Edit</a><br />
                    <a href="/Friend/DeleteFriend/@d.ID">Delete</a>
                </td>
            </tr>
        }
    }
</table>

LaboratoriskaMVC1/Views/Friend/NewFriend.cshtml
@model LaboratoriskaMVC1.Models.Friend

@{
    ViewBag.Title = "NewFriend";
}

<h2>New Friend</h2>

@using (Html.BeginForm("NewFriend", "Friend"))
{
    @Html.HiddenFor(m => m.ID)
    <div class="form-group">
        @Html.LabelFor(m => m.FriendId) @Html.TextAreaFor(m => m.FriendId, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.FriendId)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Ime) @Html.TextAreaFor(m => m.Ime, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Ime)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.MastoZiveenje) @Html.TextAreaFor(m => m.MastoZiveenje, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MastoZiveenje)
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
    @Html.ActionLink("Back", "FriendView", new { }, new { @class = "btn btn-primary" })

}

LaboratoriskaMVC1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LaboratoriskaMVC1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LaboratoriskaMVC1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

LaboratoriskaMVC1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("New Friend", "NewFriend", "Friend")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>